name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: exit 0
      # - run: yarn
      # - run: yarn build:packages
      # - run: yarn lint:all
      # - run: yarn format:diff
      # - run: yarn test
